# Generated by Django 5.1.6 on 2025-02-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.CharField(max_length=30)),
                ('distric', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('evsname', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('bookstatus', models.CharField(default='available', max_length=30)),
                ('videolink', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('uno', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('vehicle', models.CharField(max_length=30)),
                ('udob', models.CharField(max_length=30)),
                ('uphone', models.CharField(max_length=10)),
                ('uemail', models.CharField(max_length=30)),
                ('uusername', models.CharField(max_length=20)),
                ('upassword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
        migrations.CreateModel(
            name='UserBookRequest',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('distric', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('evsname', models.CharField(max_length=30)),
                ('status', models.CharField(default='created', max_length=20)),
                ('statuss', models.CharField(default='created', max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('station', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='MySecondProjectWeb.station')),
            ],
            options={
                'db_table': 'userbookrequest',
            },
        ),
    ]
